"""Agent tool boundary and the Phase 3.1 filesystem discovery tool."""

from backend_ai.core.contracts import Tool
from backend_ai.tools.base import ToolError, ToolErrorCode, ToolMetadata
from backend_ai.tools.read_file import DEFAULT_MAX_READ_BYTES, ReadFileResult, ReadFileTool, read_file
from backend_ai.tools.project_context import (
    ProjectContext,
    ProjectContextBuilder,
    ProjectContextTool,
    project_context,
)
from backend_ai.tools.project_structure import (
    DEFAULT_MAX_INSPECTED_FILES,
    DEFAULT_MAX_STRUCTURE_FILE_BYTES,
    MAX_MAX_INSPECTED_FILES,
    MAX_MAX_STRUCTURE_FILE_BYTES,
    Detection,
    DirectorySummary,
    LanguageSummary,
    ProjectStructureResult,
    ProjectStructureTool,
    project_structure,
)
from backend_ai.tools.search_code import (
    DEFAULT_MAX_FILE_BYTES,
    DEFAULT_MAX_QUERY_LENGTH,
    DEFAULT_MAX_RESULTS,
    MAX_MAX_FILE_BYTES,
    MAX_MAX_RESULTS,
    SearchCodeResult,
    SearchCodeTool,
    SearchMatch,
    search_code,
)
from backend_ai.tools.filesystem import (
    DEFAULT_IGNORED_DIRECTORIES,
    DEFAULT_MAX_DEPTH,
    DEFAULT_MAX_DIRECTORIES,
    DEFAULT_MAX_FILES,
    DiscoveredDirectory,
    DiscoveredFile,
    FileDiscoveryResult,
    ListFilesTool,
    list_files,
)

__all__ = [
    "Tool",
    "ToolError",
    "ToolErrorCode",
    "ToolMetadata",
    "DEFAULT_MAX_READ_BYTES",
    "ProjectContext",
    "ProjectContextBuilder",
    "ProjectContextTool",
    "project_context",
    "DEFAULT_MAX_INSPECTED_FILES",
    "DEFAULT_MAX_STRUCTURE_FILE_BYTES",
    "MAX_MAX_INSPECTED_FILES",
    "MAX_MAX_STRUCTURE_FILE_BYTES",
    "Detection",
    "DirectorySummary",
    "LanguageSummary",
    "ProjectStructureResult",
    "ProjectStructureTool",
    "project_structure",
    "DEFAULT_MAX_FILE_BYTES",
    "DEFAULT_MAX_QUERY_LENGTH",
    "DEFAULT_MAX_RESULTS",
    "MAX_MAX_FILE_BYTES",
    "MAX_MAX_RESULTS",
    "SearchCodeResult",
    "SearchCodeTool",
    "SearchMatch",
    "search_code",
    "ReadFileResult",
    "ReadFileTool",
    "read_file",
    "DEFAULT_IGNORED_DIRECTORIES",
    "DEFAULT_MAX_DEPTH",
    "DEFAULT_MAX_DIRECTORIES",
    "DEFAULT_MAX_FILES",
    "DiscoveredDirectory",
    "DiscoveredFile",
    "FileDiscoveryResult",
    "ListFilesTool",
    "list_files",
]
